### ISSUE TITLE
Cannot read parameter

### ISSUE THREAD

**Issue by EarlFan** [atmyers/ecp-tutorials#2]
Hello !

Thanks for the tutorial !

I find this repo today, and successfully run the Hello_world case, however, I cannot run the 02_ParmParse case correctly.

![Snipaste_2023-12-26_21-38-35](https://github.com/atmyers/ecp-tutorials/assets/24243804/776542fe-3e9e-4bed-8067-d66cb062f5f1)

I will be grateful if you help me to fix this issue, thanks !

Regards,
Fan E

**Comment by atmyers** [comment]
Hi Fan E,

Thank you for trying out these tutorials! The inputs file need to passed as the first command line argument to the executable, like so:

`
./02_ParmParse inputs
`

-Andrew

**Comment by EarlFan** [comment]
Dear Andrew,

Thanks for your help!

Regards,
Fan E
